# Generated by Django 5.1.6 on 2026-04-11 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('meta_title', models.CharField(max_length=200)),
                ('hero_headline', models.CharField(blank=True, max_length=400)),
                ('hero_subheadline', models.TextField(blank=True)),
                ('intro', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='PageStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='website.staticpage')),
            ],
            options={
                'ordering': ('page', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('body', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, help_text='Örn. ./assets/img/... — frontend statik dosya yolu', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.staticpage')),
            ],
            options={
                'ordering': ('page', 'sort_order', 'id'),
                'unique_together': {('page', 'key')},
            },
        ),
    ]
