# Generated by Django 5.1.6 on 2026-05-01 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_currency', models.CharField(default='USD', max_length=8)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('status_label', models.CharField(blank=True, max_length=80)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='projects.project')),
            ],
        ),
    ]
