# Generated by Django 5.1.6 on 2026-04-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('address', 'Address'), ('email', 'E-mail'), ('phone', 'Phone')], max_length=16)),
                ('title_label', models.CharField(max_length=80)),
                ('line_primary', models.CharField(blank=True, max_length=200)),
                ('line_secondary', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactSiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_kicker', models.CharField(blank=True, max_length=120)),
                ('intro_headline', models.CharField(blank=True, max_length=400)),
                ('intro_body', models.TextField(blank=True)),
                ('map_embed_url', models.URLField(blank=True, max_length=800)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact site profile',
                'verbose_name_plural': 'Contact site profile',
            },
        ),
    ]
