# Generated by Django 5.1.6 on 2026-05-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='source_page',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
